#!/bin/sh
# Regenerates content/docs/ from the application repository.
#
# The reference documentation has exactly one source, beside the application
# code. The website follows the configured ref (normally main), while each
# released build retains its own tagged copy in the application repository.
#
#   scripts/sync-docs.sh              # sync at the configured ref
#   scripts/sync-docs.sh --check      # fail if the tree would change
#   SIDESCOPES_DOCS_REF=v0.6.0 scripts/sync-docs.sh
#
# --check is what CI runs. It re-runs the sync into a scratch directory and
# compares, so a hand edit to content/docs/ - which would be silently
# overwritten by the next sync - fails the build instead.
set -eu

SITE=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
CODE=${SIDESCOPES_CODE_REPO:-$SITE/../sidescopes}
REF=${SIDESCOPES_DOCS_REF:-$(sed -n "s/^  docsRef = '\(.*\)'/\1/p" "$SITE/hugo.toml")}
MODE=${1:-sync}

if [ -z "$REF" ]; then
    echo "sync-docs: no docsRef in hugo.toml and no SIDESCOPES_DOCS_REF" >&2
    exit 2
fi
if [ ! -d "$CODE/.git" ]; then
    echo "sync-docs: no application repository at $CODE" >&2
    echo "  set SIDESCOPES_CODE_REPO to its checkout" >&2
    exit 2
fi
if ! git -C "$CODE" rev-parse --verify --quiet "$REF^{commit}" >/dev/null; then
    echo "sync-docs: $CODE has no ref $REF (fetch tags?)" >&2
    exit 2
fi

SHA=$(git -C "$CODE" rev-parse --short "$REF^{commit}")
TARGET=$SITE/content/docs
[ "$MODE" = "--check" ] && TARGET=$(mktemp -d)/docs && mkdir -p "$TARGET"

# source file : output name : title : weight : one-line description
SET="SCOPES.md:scopes:The scopes:10:Measurements, interpretation, trace controls, layouts, and color assumptions.
REGIONS.md:regions:Choosing a region:20:Drawing, window attachment, face selection, desktop-border editing, and multiple displays.
SHORTCUTS.md:shortcuts:Keyboard and mouse:30:Complete keyboard, mouse, color-pin, preset, and rebinding reference.
TROUBLESHOOTING.md:troubleshooting:Troubleshooting:40:Screen-capture permission, security warnings, capture recovery, preferences, and diagnostic logs."

written=0
echo "$SET" | while IFS=: read -r source name title weight description; do
    [ -n "$source" ] || continue
    body=$(git -C "$CODE" show "$REF:docs/$source" 2>/dev/null) || {
        echo "sync-docs: $REF has no docs/$source" >&2
        exit 1
    }

    # Drop the file's own H1: the page template prints the title.
    body=$(printf '%s\n' "$body" | sed '1{/^# /d;}' | sed '1{/^$/d;}')

    # Cross-links between the documents become site links; anything else
    # pointing into the repository becomes an absolute GitHub link, so a
    # reader is never sent to a path that does not exist here.
    body=$(printf '%s\n' "$body" |
        sed -e 's#](SCOPES\.md#](/docs/scopes/#g' \
            -e 's#](REGIONS\.md#](/docs/regions/#g' \
            -e 's#](SHORTCUTS\.md#](/docs/shortcuts/#g' \
            -e 's#](TROUBLESHOOTING\.md#](/docs/troubleshooting/#g' \
            -e 's#](MODULES\.md#](https://github.com/sidescopes/sidescopes/blob/'"$REF"'/docs/MODULES.md#g' \
            -e 's#](\.\./#](https://github.com/sidescopes/sidescopes/blob/'"$REF"'/#g')

    {
        printf -- '---\n'
        printf 'title: %s\n' "$title"
        printf 'weight: %s\n' "$weight"
        printf 'description: >-\n  %s\n' "$description"
        printf 'sourceFile: docs/%s\n' "$source"
        printf '# GENERATED by scripts/sync-docs.sh from %s at %s.\n' "docs/$source" "$REF"
        printf '# Edit the application repository, not this file.\n'
        printf -- '---\n\n'
        printf '%s\n' "$body"
    } > "$TARGET/$name.md"
    written=$((written + 1))
done

if [ "$MODE" = "--check" ]; then
    # _index.md is written by hand and is not part of the generated set.
    if diff -r -q -x '_index.md' "$SITE/content/docs" "$TARGET" >/dev/null 2>&1; then
        echo "sync-docs: content/docs is current for $REF ($SHA)"
    else
        echo "sync-docs: content/docs DIFFERS from $REF ($SHA)" >&2
        diff -r -x '_index.md' "$SITE/content/docs" "$TARGET" | head -40 >&2
        echo "" >&2
        echo "Run scripts/sync-docs.sh and commit the result." >&2
        exit 1
    fi
else
    echo "sync-docs: wrote content/docs from $REF ($SHA)"
fi
